language: ruby
rvm:
  - 2.1.10
  - 2.2.10 - check
  - 2.3.8 - check
  - 2.4.5 - check
  - 2.5.5 - check
  - jruby-9.1.8.0
install: "bundle install --retry=3"
gemfile:
- Gemfile.jruby
- Gemfile.ruby21
- Gemfile
matrix:
  exclude:
  - rvm: 2.1.10
    gemfile: Gemfile.jruby
  - rvm: 2.2.10
    gemfile: Gemfile.jruby
  - rvm: 2.3.8
    gemfile: Gemfile.jruby
  - rvm: 2.4.5
    gemfile: Gemfile.jruby
  - rvm: 2.5.5
    gemfile: Gemfile.jruby
  - rvm: 2.2.10
    gemfile: Gemfile.ruby21
  - rvm: 2.3.8
    gemfile: Gemfile.ruby21
  - rvm: 2.4.5
    gemfile: Gemfile.ruby21
  - rvm: 2.5.5
    gemfile: Gemfile.ruby21
  - rvm: jruby-9.1.8.0
    gemfile: Gemfile.ruby21
  - rvm: jruby-9.1.8.0
    gemfile: Gemfile
  